services:
  llama-cpp:
    image: ghcr.io/ggml-org/llama.cpp:full-cuda
    container_name: llama-cpp
    ports:
      - "${LLAMA_CPP_PORT:-12345}:${LLAMA_CPP_PORT:-12345}"
    volumes:
      - ./data/models:/models
    # Usamos el alias específico configurado en el .env
    command: >
      --server
      --model /models/${HF_FILE}
      --alias ${LLAMA_MODEL_ALIAS:-claude_local}
      --host 0.0.0.0 
      --port ${LLAMA_CPP_PORT:-12345}
      --n-gpu-layers ${LLAMA_CPP_N_GL:-all}
      --ctx-size ${LLAMA_CPP_CTX_SIZE:-32768}
      --batch-size 512 
      --ubatch-size 256
      --threads 20 
      --threads-batch 20 
      --fit on
      --flash-attn on 
      --cache-type-k q8_0 
      --cache-type-v q8_0 
      --no-mmap
      --jinja
      --reasoning on
      --temp 0.75 
      --top-p 0.95 
      --top-k 40 
      --min-p 0.05 
      --repeat-penalty 1.00
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
